// frontreact/src/pages/Login.tsx
import React, { SyntheticEvent, useState } from 'react'
import axios from 'axios';
import Home from './Home';
import User from '../types/User';
import { Link } from 'react-router-dom';

const Login = () => {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [redirect, setRedirect] = useState(false);

  const submit = async (e: SyntheticEvent) => {
    e.preventDefault();
    const res: any = await axios.post('login', {
      email: email,
      password: password
    }, { withCredentials: true });
    axios.defaults.headers.common['Authorization'] = `Bearer ${res.data.token}`;
    setRedirect(true);
    // setLogin();
  }

  if(redirect) {
    return <Home />
  }

  return (
    <>
      <form className="form-signin w-100 m-auto" onSubmit={submit}>
        <h1 className="h3 mb-3 fw-normal">Please sign in</h1>
        <div className="form-floating">
          <input type="email" className="form-control"  placeholder="Email" required onChange={e => setEmail(e.target.value)}  />
          <label htmlFor="floatingInput">Email address</label>
        </div>
        <div className="form-floating">
          <input type="password" className="form-control"  placeholder="Password" required onChange={e => setPassword(e.target.value)} />
          <label htmlFor="floatingInput">Password</label>
        </div>
        <div className="form-floating">
          <Link to="/forgot">Forgot password</Link>
        </div>
        <button className="btn btn-primary w-100 py-2" type="submit">Sign in</button>
    </form>
  </>
  )
}

export default Login

// frontangular/src/app/pages/login/login.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule } from '@angular/forms';
import { AuthService } from '../../services/auth.service';
import { Router, RouterLink, RouterModule } from '@angular/router';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [ReactiveFormsModule, RouterModule, RouterLink],
  templateUrl: './login.component.html',
  styleUrl: './login.component.scss'
})
export class LoginComponent implements OnInit{

  fb = inject(FormBuilder);
  router = inject(Router);
  authService = inject(AuthService);

  form!: FormGroup;

  ngOnInit(): void {
      this.form = this.fb.group({
        email: '',
        password: ''
      });
  }

  onSubmit() {
    this.authService.login(this.form.getRawValue())
          .subscribe( (res: any ) => {
            this.authService.accessToken = res.token;
            this.authService.authEmitter.emit(true);
            this.router.navigate(['/'])
          });
  }
}

<main class="form-signin w-100 m-auto">
  <form [formGroup]="form" (submit)="onSubmit()">
    <h1 class="h3 mb-3 fw-normal">Please sign in</h1>

    <div class="form-floating">
      <input type="email" formControlName="email" class="form-control" id="floatingInput" placeholder="name@example.com">
      <label for="floatingInput">Email address</label>
    </div>
    <div class="form-floating">
      <input type="password" formControlName="password" class="form-control" id="floatingPassword" placeholder="Password">
      <label for="floatingPassword">Password</label>
    </div>

    <div class="form-floating mb-3">
      <a routerLink="/forgot"  class="nav-link px-2">Forgot your password</a>
    </div>

    <button class="btn btn-primary w-100 py-2" type="submit">Sign in</button>
  </form>
</main>
