// frontreact/src/pages/Forgot.tsx
import React, { SyntheticEvent, useState } from 'react'
import axios from 'axios';

const Forgot = () => {

  const [email, setEmail] = useState('');
  const [notify, setNotify] = useState({
    show: false,
    error: false,
    message: ''
  });

  const submit = async (e: SyntheticEvent) => {
    e.preventDefault();
    try {
      await axios.post('forgot', { email });
      setNotify({
        show: true,
        error: false,
        message: 'Email was sent!'
      })
    } catch (error) {
      setNotify({
        show: true,
        error: true,
        message: 'Email does not exists!'
      })
    }
  }

  let info;
  if(notify.show) {
    info = (
      <div className={notify.error ? 'alert alert-danger' : 'alert alert-success'} role='alert'>
        {notify.message}
      </div>
    )
  }

  return (
    <>
      <form className="form-signin w-100 m-auto" onSubmit={submit}>
        {info}
        <h1 className="h3 mb-3 fw-normal">Please set your email</h1>
        <div className="form-floating">
          <input type="email" className="form-control"  placeholder="Email" required onChange={e => setEmail(e.target.value)}  />
          <label htmlFor="floatingInput">Email address</label>
        </div>
        <button className="btn btn-primary w-100 py-2" type="submit">Send Email</button>
    </form>
    </>
  )
}

export default Forgot

// frontangular/src/app/pages/forgot/forgot.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule } from '@angular/forms';
import { ForgotService } from '../../services/forgot.service';

@Component({
  selector: 'app-forgot',
  standalone: true,
  imports: [ReactiveFormsModule],
  templateUrl: './forgot.component.html',
  styleUrl: './forgot.component.scss'
})
export class ForgotComponent implements OnInit {
  fb = inject(FormBuilder);
  forgotService = inject(ForgotService);

  form!: FormGroup;
  cls = '';
  message = '';

  ngOnInit(): void {
      this.form = this.fb.group({
        email: ''
      });
  }

  onSubmit() {
    this.forgotService.forgot(this.form.getRawValue())
          .subscribe( (data ) => {
            this.cls = 'success';
            this.message = 'email was sent!'
          }, (err) => {
            this.cls = 'danger';
            this.message = 'Error occurs!'
          } )
  }
}

<main class="form-signin w-100 m-auto">
    @if(cls) {
      <div class="alert alert-{{cls}}" role="alert">{{message}}</div>
    }

  <form [formGroup]="form" (submit)="onSubmit()">
    <h1 class="h3 mb-3 fw-normal">Forgot password</h1>

    <div class="form-floating">
      <input type="email" formControlName="email" class="form-control" id="floatingInput" placeholder="name@example.com">
      <label for="floatingInput">Email address</label>
    </div>

    <button class="btn btn-primary w-100 py-2" type="submit">Send email</button>
  </form>
</main>
