// frontreact/src/pages/Register.tsx
import React, { SyntheticEvent, useState } from 'react';
import axios from 'axios';
import Login from './Login';

const Register = ( ) => {
  const [firstName, setFirstName] = useState('');
  const [lastName, setLastName] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [passwordConfirm, setPasswordConfirm] = useState('');
  const [redirect, setRedirect] = useState(false);

  const submit = async (e: SyntheticEvent) => {

    e.preventDefault();
    const res = await axios.post('register', {
      first_name: firstName,
      last_name: lastName,
      email: email,
      password: password,
      password_confirm: passwordConfirm
    });
    setRedirect(true);
  }

  if(redirect) {
    return <Login />
  }

  return (
    <>
      <form className="form-signin w-100 m-auto" onSubmit={submit}>
        <div className="form-floating">
          <input type="text" className="form-control" placeholder="First name" required  onChange={e => setFirstName(e.target.value)}/>
          <label htmlFor="floatingInput">First Name</label>
        </div>
        <div className="form-floating">
          <input type="text" className="form-control"  placeholder="Last name" required onChange={e => setLastName(e.target.value)} />
          <label htmlFor="floatingInput">Last Name</label>
        </div>
        <div className="form-floating">
          <input type="email" className="form-control"  placeholder="Email" required onChange={e => setEmail(e.target.value)} />
          <label htmlFor="floatingInput">Email address</label>
        </div>
        <div className="form-floating">
          <input type="password" className="form-control"  placeholder="Password" required onChange={e => setPassword(e.target.value)}/>
          <label htmlFor="floatingInput">Password</label>
        </div>
        <div className="form-floating">
          <input type="password" className="form-control"  placeholder="Password confirm" required onChange={e => setPasswordConfirm(e.target.value)}/>
          <label htmlFor="floatingInput">Password confirm</label>
        </div>
        <button className="btn btn-primary w-100 py-2" type="submit">Register</button>
    </form>
  </>
  )
}

export default Register

// frontangular/src/app/pages/register/register.component.ts

import { Component, inject, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-register',
  standalone: true,
  imports: [ReactiveFormsModule],
  templateUrl: './register.component.html',
  styleUrl: './register.component.scss'
})
export class RegisterComponent implements OnInit{

  fb = inject(FormBuilder);
  router = inject(Router);
  authService = inject(AuthService);

  form!: FormGroup;

  ngOnInit(): void {
      this.form = this.fb.group({
        first_name: '',
        last_name: '',
        email: '',
        password: '',
        password_confirm: ''
      });
  }

  onSubmit() {
    this.authService.register(this.form.getRawValue())
        .subscribe( (data) => this.router.navigate(['/login'])  )
  }

}

<main class="form-signin w-100 m-auto">
  <form [formGroup]="form" (submit)="onSubmit()">
    <h1 class="h3 mb-3 fw-normal">Please register</h1>

    <div class="form-floating">
      <input type="text" formControlName="first_name" class="form-control" id="floatingInput" placeholder="First Name">
      <label for="floatingInput">First name</label>
    </div>
    <div class="form-floating">
      <input type="text" formControlName="last_name" class="form-control" id="floatingInput" placeholder="Last Name">
      <label for="floatingInput">Last name</label>
    </div>
    <div class="form-floating">
      <input type="email" formControlName="email" class="form-control" id="floatingInput" placeholder="name@example.com">
      <label for="floatingInput">Email address</label>
    </div>
    <div class="form-floating">
      <input type="password" formControlName="password" class="form-control" id="floatingPassword" placeholder="Password">
      <label for="floatingPassword">Password</label>
    </div>
    <div class="form-floating">
      <input type="password" formControlName="password_confirm" class="form-control" id="floatingPassword" placeholder="Password Confirm">
      <label for="floatingPassword">Password confirm</label>
    </div>

    <button class="btn btn-primary w-100 py-2" type="submit">Register</button>
  </form>
</main>
