// frontreact/src/pages/Reset.tsx
import React, { SyntheticEvent, useState } from 'react'
import axios from 'axios';
import { useParams } from 'react-router-dom'
import Home from './Home';

const Reset = () => {

  const params = useParams();

  const [password, setPassword] = useState('');
  const [passwordConfirm, setPasswordConfirm] = useState('');
  const [redirect, setRedirect] = useState(false);

  const submit = async (e: SyntheticEvent) => {
    e.preventDefault();
    const token =params.token;
    await axios.post('reset', {
      token,
      password,
      password_confirm:  passwordConfirm
    });
    setRedirect(true);
  }

  if(redirect) {
    return <Home />
  }

  return (
    <>
      <form className="form-signin w-100 m-auto" onSubmit={submit}>
        <h1 className="h3 mb-3 fw-normal">Please set your email</h1>
        <div className="form-floating">
          <input type="password" className="form-control"  placeholder="Password" required onChange={e => setPassword(e.target.value)} />
          <label htmlFor="floatingInput">Password</label>
        </div>
        <div className="form-floating">
          <input type="password" className="form-control"  placeholder="Password Confirm" required onChange={e => setPasswordConfirm(e.target.value)} />
          <label htmlFor="floatingInput">Password confirm</label>
        </div>
        <button className="btn btn-primary w-100 py-2" type="submit">Reset password</button>
    </form>
    </>
  )
}

export default Reset

// frontangular/src/app/pages/reset/reset.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule } from '@angular/forms';
import { ForgotService } from '../../services/forgot.service';
import { ActivatedRoute, Router, RouterModule } from '@angular/router';

@Component({
  selector: 'app-reset',
  standalone: true,
  imports: [ReactiveFormsModule, RouterModule],
  templateUrl: './reset.component.html',
  styleUrl: './reset.component.scss'
})
export class ResetComponent implements OnInit{

  fb = inject(FormBuilder);
  forgotService = inject(ForgotService);
  route = inject(ActivatedRoute);
  router = inject(Router);

  form!: FormGroup;

  ngOnInit(): void {
      this.form = this.fb.group({
        password: '',
        password_confirm: ''
      });
  }

  onSubmit() {
    const formData = this.form.getRawValue();
    const data = {
      ...formData,
      token: this.route.snapshot.params['token']
    }
    this.forgotService.reset(data).subscribe( (data ) => {
        this.router.navigate(['/login'])
     } )
  }
}

<main class="form-signin w-100 m-auto">
  <form [formGroup]="form" (submit)="onSubmit()">
    <h1 class="h3 mb-3 fw-normal">Reset your password</h1>

    <div class="form-floating">
      <input type="password" formControlName="password" class="form-control" id="floatingPassword" placeholder="Password">
      <label for="floatingPassword">Password</label>
    </div>
    <div class="form-floating">
      <input type="password" formControlName="password_confirm" class="form-control" id="floatingPassword" placeholder="Password Confirm">
      <label for="floatingPassword">Password confirm</label>
    </div>

    <button class="btn btn-primary w-100 py-2" type="submit">Submit</button>
  </form>
</main>
